import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname } from "node:path";
const CHROME="/Users/hau/.cache/puppeteer/chrome/mac_arm-146.0.7680.76/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const MIME={".html":"text/html",".js":"text/javascript",".glb":"model/gltf-binary",".wasm":"application/wasm"};
const s=createServer(async(req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";const f=join(process.cwd(),p);if(!existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":MIME[extname(f)]||"application/octet-stream"});res.end(await readFile(f));});
await new Promise(r=>s.listen(8185,r));
const {default:P}=await import("../.claude/skills/unity-poc/scripts/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js");
const b=await P.launch({executablePath:CHROME,headless:"new",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader"]});
const pg=await b.newPage();await pg.setViewport({width:870,height:720,deviceScaleFactor:2});
const errs=[];pg.on("console",m=>m.type()==="error"&&errs.push(m.text()));pg.on("pageerror",e=>errs.push("PAGEERR:"+e.message));
await pg.goto("http://localhost:8185/",{waitUntil:"networkidle0"});await new Promise(r=>setTimeout(r,1200));
await pg.evaluate(()=>{window.GAME.squad.count=25; window.GAME._enterBoss();});
const spawn=await pg.evaluate(()=>({bossHpAtSpawn:Math.round(window.GAME.boss.hp)}));
await new Promise(r=>setTimeout(r,3000));
const st=await pg.evaluate(()=>({bossHp:Math.round(window.GAME.boss?.hp??-1),bossZ:+(window.GAME.boss?.z??0).toFixed(1),adds:window.GAME.enemies.activeCount,bullets:window.GAME.bullets.activeCount,count:Math.floor(window.GAME.squad.count)}));
await pg.screenshot({path:"bigboss-shot.png"});
await b.close();s.close();console.log("spawn",JSON.stringify(spawn));console.log("after3s",JSON.stringify(st),"errors:",errs.length?errs:"none");
