import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname } from "node:path";
const CHROME="/Users/hau/.cache/puppeteer/chrome/mac_arm-146.0.7680.76/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const MIME={".html":"text/html",".js":"text/javascript",".glb":"model/gltf-binary",".wasm":"application/wasm"};
const s=createServer(async(req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";const f=join(process.cwd(),p);if(!existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":MIME[extname(f)]||"application/octet-stream"});res.end(await readFile(f));});
await new Promise(r=>s.listen(8182,r));
const {default:P}=await import("../.claude/skills/unity-poc/scripts/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js");
const b=await P.launch({executablePath:CHROME,headless:"new",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader"]});
const pg=await b.newPage();const errs=[];
pg.on("console",m=>m.type()==="error"&&errs.push(m.text()));pg.on("pageerror",e=>errs.push("PAGEERR:"+e.message));
await pg.goto("http://localhost:8182/",{waitUntil:"networkidle0"});
await new Promise(r=>setTimeout(r,1500));
// force boss right now
await pg.evaluate(()=>window.GAME._enterBoss());
const before=await pg.evaluate(()=>({state:window.GAME.state,bossHp:window.GAME.boss?.hp,bossZ:+window.GAME.boss?.z.toFixed(1),squadZ:+window.GAME.squad.z.toFixed(1),count:Math.floor(window.GAME.squad.count),bullets:window.GAME.bullets.activeCount,fireInt:window.GAME.squad.fireInterval}));
await new Promise(r=>setTimeout(r,2500));
const after=await pg.evaluate(()=>({bossHp:window.GAME.boss?.hp,bossZ:+(window.GAME.boss?.z??0).toFixed(1),bullets:window.GAME.bullets.activeCount,fireTimer:+window.GAME.squad.fireTimer.toFixed(3),count:Math.floor(window.GAME.squad.count)}));
await b.close();s.close();
console.log("BEFORE",JSON.stringify(before));
console.log("AFTER ",JSON.stringify(after));
console.log("errors:",errs.length?errs:"none");
