import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname } from "node:path";
const CHROME="/Users/hau/.cache/puppeteer/chrome/mac_arm-146.0.7680.76/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const MIME={".html":"text/html",".js":"text/javascript",".glb":"model/gltf-binary",".wasm":"application/wasm"};
const s=createServer(async(req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";const f=join(process.cwd(),p);if(!existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":MIME[extname(f)]||"application/octet-stream"});res.end(await readFile(f));});
await new Promise(r=>s.listen(8179,r));
const {default:P}=await import("../.claude/skills/unity-poc/scripts/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js");
const b=await P.launch({executablePath:CHROME,headless:"new",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader"]});
const pg=await b.newPage();await pg.setViewport({width:720,height:720,deviceScaleFactor:2});
await pg.goto("http://localhost:8179/",{waitUntil:"networkidle0"});
await new Promise(r=>setTimeout(r,3000));
const info=await pg.evaluate(()=>{const g=window.GAME;g.loop.stop();
 const m=g.soldiers.mesh.material;m.map=null;m.emissive?.set(0xff2222);m.emissiveIntensity=1;m.color.set(0xff2222);m.needsUpdate=true;
 // sample first 3 soldier instance world positions from data
 const ds=[0,1,2].map(i=>({x:+g.soldiers.data[i].x.toFixed(2),y:+g.soldiers.data[i].y.toFixed(2),z:+g.soldiers.data[i].z.toFixed(2)}));
 const z=g.squad.z;
 g.camera.position.set(0,4,z-6);g.camera.lookAt(0,0.5,z-1);
 g.renderer.render(g.scene,g.camera);
 return {ds, squadZ:+z.toFixed(2), centroid:+g.squad.centroidX.toFixed(2)};});
console.log(JSON.stringify(info));
await pg.screenshot({path:"locate-shot.png"});await b.close();s.close();
