import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname } from "node:path";
const CHROME="/Users/hau/.cache/puppeteer/chrome/mac_arm-146.0.7680.76/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const MIME={".html":"text/html",".js":"text/javascript",".glb":"model/gltf-binary",".wasm":"application/wasm"};
const s=createServer(async(req,res)=>{let p=decodeURIComponent(req.url.split("?")[0]);if(p==="/")p="/index.html";const f=join(process.cwd(),p);if(!existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{"Content-Type":MIME[extname(f)]||"application/octet-stream"});res.end(await readFile(f));});
await new Promise(r=>s.listen(8186,r));
const {default:P}=await import("../.claude/skills/unity-poc/scripts/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js");
const b=await P.launch({executablePath:CHROME,headless:"new",args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader"]});
const pg=await b.newPage();await pg.setViewport({width:390,height:844,deviceScaleFactor:2});
await pg.goto("http://localhost:8186/",{waitUntil:"networkidle0"});await new Promise(r=>setTimeout(r,1500));
const tris=await pg.evaluate(()=>{const t=g=>{const ix=g.index?g.index.count/3:g.attributes.position.count/3;return Math.round(ix);};
 return {soldier:t(window.GAME.soldiers.mesh.geometry),enemy:t(window.GAME.enemies.mesh.geometry)};});
// measure fps: count rAF over 1s via a hook
const fps=await pg.evaluate(()=>new Promise(res=>{let n=0;const t0=performance.now();function f(){n++;if(performance.now()-t0<1000)requestAnimationFrame(f);else res(n);}requestAnimationFrame(f);}));
const d0=await pg.evaluate(()=>window.GAME.distance);
await new Promise(r=>setTimeout(r,1000));
const d1=await pg.evaluate(()=>window.GAME.distance);
await b.close();s.close();
console.log("tris",JSON.stringify(tris));console.log("headless fps ~",fps);console.log("sim advanced (m/s wall)",+(d1-d0).toFixed(2),"(expected ~14)");
