using System.Collections.Generic;
using UnityEngine;

namespace Fighter3D
{
    // Job-specific content for the 3D ARENA CLASH vertical slice — the 3D analogue of the 2D
    // fighter's Game/ layer. Registers the roster and boots with zero scene authoring. Three
    // fighters exercise the three install archetypes + a projectile:
    //   RIDGE  : MeterBuff install (timed rushdown buff)
    //   VESPER : StanceSwap        (toggle moveset)
    //   ORBIT  : projectile zoning (PACKET-style)
    // modelId points at a GLB under Assets/Resources/Models/<id>.bytes (generated by the
    // game-asset-gen 3D path); absent => tinted primitive capsule, build still runs.
    public static class ArenaClash3D
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Boot()
        {
            StoryText3D.gameTitle = "ARENA CLASH 3D";
            StoryText3D.premise =
                "Three styles meet on the ring.\n"
                + "Rushdown, shadow, and zoning — one leaves standing.";
            Roster3D.All = BuildRoster();
            new GameObject("Game").AddComponent<GameBootstrap3D>();
        }

        // Public so the headless playtest/build can construct the same roster without booting.
        public static List<CharacterDef3D> BuildRoster() =>
            new List<CharacterDef3D> { Ridge(), Vesper(), Orbit() };

        static MoveData3D Light(float reach = 1.0f) =>
            new MoveData3D { name = "Jab", startup = 5, active = 3, recovery = 9, damage = 60, hitstun = 14, blockstun = 8, knockback = 2.5f, reach = reach, height = 1.1f, radius = 0.7f, hitstop = 5 };

        static MoveData3D Heavy(float reach = 1.25f) =>
            new MoveData3D { name = "Smash", startup = 9, active = 4, recovery = 16, damage = 120, hitstun = 20, blockstun = 12, knockback = 5f, reach = reach, height = 1.1f, radius = 0.85f, hitstop = 8 };

        // ---- RIDGE: rushdown + MeterBuff install ----
        static CharacterDef3D Ridge()
        {
            return new CharacterDef3D
            {
                id = "ridge",
                displayName = "Ridge",
                faction = "RUSH",
                tagline = "adaptive rushdown / install",
                lore = "Hits first, asks never.",
                modelId = "ridge",
                bodyColor = new Color(0.75f, 0.25f, 0.20f),
                accentColor = new Color(1f, 0.6f, 0.3f),
                walkSpeed = 3.6f,
                dashSpeed = 8.2f,
                maxHealth = 1000,
                light = Light(),
                heavy = Heavy(),
                special = new MoveData3D { name = "Lunge", kind = MoveKind.Special, startup = 12, active = 5, recovery = 20, damage = 150, hitstun = 24, knockback = 6f, knockdown = true, reach = 1.6f, height = 1.0f, radius = 0.9f, hitstop = 10 },
                super = new MoveData3D { name = "Avalanche", kind = MoveKind.Super, startup = 6, active = 6, recovery = 26, damage = 320, hitstun = 30, knockback = 8f, knockdown = true, reach = 1.8f, height = 1.1f, radius = 1.2f, hitstop = 16 },
                installType = InstallType.MeterBuff,
                installName = "OVERDRIVE",
                installMeterCost = 50,
                installDuration = 8f,
                installSpeedMult = 1.3f,
                installDamageMult = 1.25f,
                installColor = new Color(1f, 0.5f, 0.4f),
            };
        }

        // ---- VESPER: StanceSwap ----
        static CharacterDef3D Vesper()
        {
            return new CharacterDef3D
            {
                id = "vesper",
                displayName = "Vesper",
                faction = "SHADE",
                tagline = "stance shifting",
                lore = "Two silhouettes, one intent.",
                modelId = "vesper",
                bodyColor = new Color(0.30f, 0.30f, 0.55f),
                accentColor = new Color(0.6f, 0.8f, 1f),
                stanceBColor = new Color(0.12f, 0.12f, 0.2f),
                stanceBName = "Umbra",
                maxHealth = 950,
                light = Light(),
                heavy = Heavy(1.2f),
                special = new MoveData3D { name = "Veil Cut", kind = MoveKind.Special, startup = 10, active = 4, recovery = 18, damage = 130, hitstun = 22, knockback = 5f, reach = 1.5f, height = 1.1f, radius = 0.85f, hitstop = 9 },
                super = new MoveData3D { name = "Eclipse", kind = MoveKind.Super, startup = 7, active = 6, recovery = 24, damage = 300, hitstun = 28, knockback = 7f, knockdown = true, reach = 1.7f, height = 1.1f, radius = 1.1f, hitstop = 16 },
                altLight = new MoveData3D { name = "Shade Jab", startup = 4, active = 3, recovery = 8, damage = 55, hitstun = 13, knockback = 2f, reach = 1.1f, height = 1.1f, radius = 0.75f, hitstop = 5 },
                altHeavy = new MoveData3D { name = "Umbra Slam", startup = 11, active = 5, recovery = 18, damage = 140, hitstun = 22, knockback = 6f, knockdown = true, reach = 1.3f, height = 1.0f, radius = 0.95f, hitstop = 10 },
                altSpecial = new MoveData3D { name = "Phase Strike", kind = MoveKind.Special, startup = 8, active = 4, recovery = 16, damage = 120, hitstun = 20, knockback = 5f, reach = 1.6f, height = 1.1f, radius = 0.85f, hitstop = 9 },
                installType = InstallType.StanceSwap,
                installName = "UMBRA",
            };
        }

        // ---- ORBIT: projectile zoning ----
        static CharacterDef3D Orbit()
        {
            return new CharacterDef3D
            {
                id = "orbit",
                displayName = "Orbit",
                faction = "ZONE",
                tagline = "projectile zoning",
                lore = "Keeps the distance honest.",
                modelId = "orbit",
                bodyColor = new Color(0.25f, 0.55f, 0.45f),
                accentColor = new Color(0.5f, 1f, 0.8f),
                walkSpeed = 3.0f,
                maxHealth = 920,
                light = Light(),
                heavy = Heavy(1.15f),
                special = new MoveData3D { name = "Packet", kind = MoveKind.Special, startup = 10, active = 3, recovery = 18, damage = 90, hitstun = 18, knockback = 4f, projectile = true, projectileSpeed = 11f, projectileLife = 1.8f, projectileRadius = 0.45f, reach = 0.9f, height = 1.1f, hitstop = 6 },
                super = new MoveData3D { name = "Barrage", kind = MoveKind.Super, startup = 8, active = 3, recovery = 22, damage = 220, hitstun = 24, knockback = 6f, projectile = true, projectileSpeed = 13f, projectileLife = 2.2f, projectileRadius = 0.6f, reach = 0.9f, height = 1.2f, hitstop = 14 },
                installType = InstallType.None,
            };
        }
    }
}
